---
- name: create .ssh directory
  become: true
  become_user: root
  file:
    path: /home/isucon/.ssh
    state: directory
    owner: isucon
    group: isucon
    mode: 0700

- name: put authorized_keys
  become: true
  become_user: root
  authorized_key:
    user: isucon
    key: "{{ lookup('file', 'authorized_keys') }}"
